let name="ABHISHEK";
let Class="12th";
let Roll_No=10;
let section="A";
let grade="A";
let math=80;
let eng=75;
let hindi=80;
console.log("\n\n****************          *******************");
console.log("                GRADE CARD                  ");
console.log("****************          *******************\n");
console.log("Student name is           ",name);
console.log("Student class is          ",Class);
console.log("Student Roll No is        ",Roll_No);
console.log("Student Section is        ",section);
console.log("Student Grade is          ",grade);

console.log("\n\n**************  MARKS  *******************\n");
console.log("   MATHS   "+math+"   ENGLISH "+eng+"   hindi   "+hindi);
console.log("\n   TOTAL MARKS   ",(math+eng+hindi));